### PR TITLE
Issue-9: Move LEDs, breakout unused pins

### PR DESCRIPTION
**Pull request by Aloz1**
Ticks off activity 1 & 2 from Issue #9

### CODE REVIEW

**Comment by ChrisAlphabet** [comment]
G'day @Aloz1 
Thanks for the PR! There are probably a few too many traces routed on the bottom layer for my taste, I tend to try and keep the bottom layer as an unbroken ground plane (beaten into me as an EE student). I think with a few minor tweaks it will be straight-forward to route most of the signals on the top layer though. Basically just separating out the SPI/UART/GPIO to there own connectors will do the trick.
Normally I would just share-screen and show you what I mean, but in the outside world I don't know what the best way is for us to do this. 
Maybe I'll just make the changes on a branch and show you what I mean.

**Comment by ChrisAlphabet** [comment]
Ahh, it also looks like the RGB LED has been swapped to pins that aren't PWM capable.
They were on pins D9, D10 and D11 but were moved to pins D7, D8, and D9 as D10 and D11 are also required for SPI.

**Comment by Aloz1** [comment]
Ah, thanks for that.

All good, I get what you mean. I'll have a play around and try to rework it with all traces on top.

Oh, good spot. Thanks for that. Hadn't realized the RGB needed PWM. I'll move that while I'm at it.

**Comment by ChrisAlphabet** [comment]
Ive got a branch in progress that has done some of the re-routing etc that you might be able to build on?

**Comment by ChrisAlphabet** [comment]
Have a look at https://github.com/ChrisAlphabet/ghost-bot/tree/feature/issue-6-hardware-updates-rework-routing, which was branched from Aloz1:feature/issue-6-hardware-updates. I think the combination of both our changes looks pretty good :)

**Comment by ChrisAlphabet** [comment]
Hey @Aloz1, do you know when you are able to take a look at this? I would like to get the boards sent away this weekend so I can put the word out for the comp if that is possible

**Comment by Aloz1** [comment]
Hey Chris, thanks. Looks great. Sorry for the delay.

I've made some minor trace adjustments to resolve some GND thermal relief errors (nothing critical, just KiCad complaining). Is the same as your changes otherwise.

**Comment by ChrisAlphabet** [comment]
Thanks for contributing @Aloz1! I'll merge in this branch and have a play with sorting out the PWM pins and silkscreen

**Pull request merged**
